### ISSUE TITLE
lfe ltest seems to not compile ltest

### ISSUE THREAD

**Issue by Phantasus** [lfe/rebar3_lfe#77] opened 2023-04-05 08:21 UTC
`rebar3_lfe` (0.4.3)

seems to be not compiling ltest for some reason, which then causes that the "as test lfe ltest"
command fails with. This could be not the actual reason as it fails, as I don't know the
architecture of ltest and `rebar3_lfe` to verify this. It seems just an interesting coincidence,
that when recompiling ltest by hand and copying the beam files into the ltest build directory,
that the following errors are "fixed":

```
===> Uncaught error in rebar_core. Run with DIAGNOSTIC=1 to see stacktrace or consult rebar3.crashdump
===> When submitting a bug report, please include the output of `rebar3 report "your command"`
```

crashdump:

```
Error: undef
[{ltest,'default-opts',[],[]},
 {rebar3_lfe_prv_ltest,find_ltest_options,1,
                       [{file,"/home/user/project/_build/default/plugins/rebar3_lfe/src/rebar3_lfe_prv_ltest.erl"},
                        {line,101}]},
 {rebar3_lfe_prv_ltest,test,1,
                       [{file,"/home/user/project/_build/default/plugins/rebar3_lfe/src/rebar3_lfe_prv_ltest.erl"},
                        {line,92}]},
 {rebar_core,do,2,
             [{file,"/home/runner/work/rebar3/rebar3/src/rebar_core.erl"},
              {line,155}]},
 {rebar_prv_do,do_task,5,
               [{file,"/home/runner/work/rebar3/rebar3/src/rebar_prv_do.erl"},
                {line,87}]},
 {rebar_core,do,2,
             [{file,"/home/runner/work/rebar3/rebar3/src/rebar_core.erl"},
              {line,155}]},
 {rebar_prv_do,do_task,5,
               [{file,"/home/runner/work/rebar3/rebar3/src/rebar_prv_do.erl"},
                {line,87}]},
 {rebar_core,do,2,
             [{file,"/home/runner/work/rebar3/rebar3/src/rebar_core.erl"},
              {line,155}]}]
```

rebar3 report:

```
Rebar3 report                                                                                         
 version 3.18.0
 generated at 2023-04-05T08:12:53+00:00
=================
Please submit this along with your issue at https://github.com/erlang/rebar3/issues (and feel free to edit out 
private information, if any)
-----------------      
Task: as  
Entered as:                                                                                                      as test lfe ltest                                                                                            -----------------                                                                                              Operating System: x86_64-pc-linux-gnu                                                                          ERTS: Erlang/OTP 25 [erts-13.1] [source] [64-bit] [smp:16:4] [ds:16:4:10] [async-threads:1] [jit:ns]
Root Directory: /usr/lib/erlang
Library directory: /usr/lib/erlang/lib
-----------------
Loaded Applications:
bbmustache: 1.12.2
certifi: 2.8.0
cf: 0.3.1
common_test: 1.23.1
compiler: 8.2.1
crypto: 5.1.2
cth_readable: 1.5.1
dialyzer: 5.0.2
edoc: 1.2
erlware_commons: 1.5.0
eunit: 2.8
eunit_formatters: 0.5.0
getopt: 1.0.1
inets: 8.1
kernel: 8.5
providers: 1.9.0
public_key: 1.13.1
relx: 4.6.0
sasl: 4.2
snmp: 5.13.1
ssl_verify_fun: 1.1.6
stdlib: 4.1
syntax_tools: 3.0
tools: 3.5.3

-----------------
Escript path: undefined
Providers:
  app_discovery as check clean clean clean-all clean-build clean-cache cmd compile compile compile confabulate 
consolidate_protocols cover coverage ct cut deps dialyzer do docs edoc escriptize escriptize eunit get-deps hel
p install install_deps key lint list lock ltest new owner path pkgs publish release release relup repl repo rep
ort repos retire revert run run-escript run-release search shell state tar tree unlock update upgrade upgrade u
pgrade user version versions xref 

```

**Comment by diasbruno** [comment] 2023-06-22 20:01
This problem happens on the latest versions of rebar3_lfe, ltest and lfe. After installing rebar3_lfe globally, tests run as expected.

**Comment by diasbruno** [comment] 2023-06-22 20:33
rebar3_lfe version 0.3.0 used on the template is boggus. Updating to `0.4.3` solves the issue.

**Comment by wmealing** [comment] 2023-07-03 14:16
> rebar3_lfe version 0.3.0, that is referenced on `master`, is boggus. Updating to `0.4.3` solves the issue.

Updating it in which repos rebar.config ? I'm pretty sure i'm facing the same problem.

**Comment by oubiwann** [comment] 2023-07-04 15:36
I messaged a question on Slack for details, but found a project I've got that's a bit older and hasn't been updated to use LFE 2.1.1.

Here are my observations ...

* Updating only LFE from 2.0.1 to 2.1.1:
  * still using rebar3_lfe 0.3.0
  * I see the old bug from #69 (`enoent`) when compiling LFE
  * tests run just fine
* Updated LFE to 2.1.1 and rebar3_lfe to 0.4.3:
  * LFE compiles w/o issue
  * still using ltest 0.13.1
  * test run fails (diagnostics show this is due to `Uncaught error: undef`)
* Update LFE to 2.1.1, rebar3_lfe to 0.4.3, and ltest to 0.13.3:
  * test run fails (diagnostics show this is due to `Uncaught error: undef`)

It seems that the `undef` error (rebar3_lfe not being able to find the function `ltest:default-opts`) is due to ltest not being compiled in the rebar3 `test` profile, plugins subdir.

Upon examination, I believe this is due to a change that was made in a "recent" version of ltest to remove cyclic dependencies between ltest, rebar3_lfe, and other plugins/projects that depended upon either of these. As a result, ltest adopted the same compile strategy as LFE (copied from LFE's `rebar.config` file).

I've created a ticket here to track progress on this:
* https://github.com/lfex/ltest/issues/74

**Comment by oubiwann** [comment] 2023-07-04 16:41
See the ticket linked in my last comment for an update on the root cause.

**Comment by oubiwann** [comment] 2023-07-04 17:11
For thoroughness, the root cause was a change in LFE (from 2.0.1 -> 2.1.1) where `lfe` was no longer used to run the compiler script, rather `lfescript` started being used.

There are new versions or ltest and rebar3_lfe published that account for this change:
* https://hex.pm/packages/ltest
* https://hex.pm/packages/rebar3_lfe

Let me know how it goes, and we can close up these tickets ... 😄

**Comment by oubiwann** [comment] 2023-07-04 17:34
I have confirmed with two projects I used to track down the bug that the fix works for them (their tests are now compiling and their CI/CDs are running successfully).

**Comment by oubiwann** [comment] 2023-07-05 02:50
Okay, been testing this all day on lots of different projects/repos, and it's looking good.

Here's what you need to do at your end to test:
* `rm -rf rebar.lock _build`
* edit your `rebar.config` file(s) to get the latest dep versions for ltest (0.13.4) and rebar3_lfe (0.4.4)
* if you follow the same rebar3 profile pattern as several of the LFE projects, run `rebar3 as test do compile,lfe ltest -tall`
* if you just have ltest and rebar3_lfe as top-level (non-profile) deps and plugins, then run `rebar3 do compile,lfe ltest -tall`
* make sure that your `_build/test/lib/ltest/ebin` and/or `_build/default/lib/ltest/ebin` directories have 10 ltest `*.beam` files in them

Given the fairly extensive testing I have done on this today, I'm going to close this as "fixed". 

If you continue to have issues, ping me in Slack or create a new issue for rebar3_lfe here (or if you think it's ltest, create a new issue here: https://github.com/lfex/ltest/issues).

**Closed by oubiwann** 2023-07-05 02:50 UTC
Labels: bug, status:released

**Comment by wmealing** [comment] 2023-07-05 03:11
I can confirm the last set of instructions solved the issue for me.

**Comment by diasbruno** [comment] 2023-07-05 11:10
Yep. I've tested here and it solved the problem!
